cppclient:
	g++ -std=c++11 cppclient.cpp -I ~/Downloads/boost_1_61_0/~/Downloads/boost_1_61_0/include/boost -I ~/socket.io-client-cpp/build/include -L ~/socket.io-client-cpp/build/lib/Release -lsioclient -lsioclient_tls -lboost_date_time -lboost_random -lboost_system -lpthread -o cppclient

clean:
	rm cppclient
